sudo: enabled
language: python
python:
  - "3.8"
script:
  - pytest -v -s --cov=Chapter02 --cov-report term-missing
before_script:
  - echo "Menjalankan Testing"
install:
  - pip install -r requirements.txt
before_install:
  - git status